apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: custom-microservice-archetype
  description: Sample service for creating a archetype microservice with all the plumbing needed
spec:
  type: service
  lifecycle: dev
  owner: user-team
